# 몹(e.g. 좀비) 자연적으로 스폰할 월드
적용할월드_목록: []
# 단위: 초
몹스폰_주기: 5

# 0~100%.  개별스폰 확률 = 100% - 밀집스폰 확률
밀집스폰_확률: 30
# 밀집스폰 될 때 스폰 될 몹의 최소~최대 수
밀집스폰_몹_수_범위: 2~6


# < 넉백 >
# 넉백A: 약간 떴다가 바닥으로 내리꼽는 느낌
넉백A_적용월드_목록: []
넉백A_강도: 0.1

# 넉백B: 위로 뜨는거 없이 약간만 밀려남
넉백B_적용월드_목록: []
넉백B_강도: 0.3
